import os
import warnings
import logging
from dotenv import load_dotenv
from sqlalchemy import create_engine, text, Engine, NVARCHAR, DECIMAL
from urllib.parse import quote_plus
import pandas as pd
import numpy as np

logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s | %(levelname)s | DatabaseSetup | %(message)s")

warnings.filterwarnings('ignore')
load_dotenv()


# -------------------- Connections --------------------
def get_engine(server_env, db_env, user_env, pw_env) -> Engine:
    conn_string = (
        f"DRIVER={os.getenv('AZURE_ODBC_DRIVER', '{ODBC Driver 18 for SQL Server}')};"
        f"SERVER={os.getenv(server_env)};"
        f"DATABASE={os.getenv(db_env)};"
        f"UID={os.getenv(user_env)};"
        f"PWD={os.getenv(pw_env)};"
        f"Encrypt=yes;"
        f"TrustServerCertificate=yes;"
    )
    quoted = quote_plus(conn_string)
    engine = create_engine(f'mssql+pyodbc:///?odbc_connect={quoted}')
    logging.info(f'Connected to {os.getenv(db_env)} at {os.getenv(server_env)}')
    return engine

def source_db_conn(): return get_engine('AZURE_SERVER','AZURE_DATABASE','AZURE_USERNAME','AZURE_PASSWORD')
def target_db_conn(): return get_engine('STAGE_SERVER','STAGE_DATABASE','STAGE_USERNAME','STAGE_PASSWORD')


# -------------------- Main --------------------
def main():

    target = target_db_conn()

    try:
        with target.begin() as conn:  # Transaction-safe

            conn.execute(text("""
                -- Data Management
                CREATE TABLE [app].[SyncItems] (
                    [OldItemID]  BIGINT         PRIMARY KEY,
                    [CategoryID] BIGINT         NULL,
                    [Name]       NVARCHAR (MAX) NULL,
                );

                CREATE TABLE [app].[SyncCategories] (
                    [OldCategoryID] BIGINT         PRIMARY KEY,
                    [AccountID]     BIGINT         NULL,
                    [Name]          NVARCHAR (MAX) NULL
                );

                CREATE TABLE [app].[SyncCities] (
                    [OldCityID]  BIGINT         PRIMARY KEY,
                    [CityID] BIGINT         NULL,
                    [CountryID] BIGINT         NULL
                );

                CREATE TABLE [app].[SyncAmenities] (
                    [OldAmenitiesID]  BIGINT         PRIMARY KEY,
                    [AmenitiesID] BIGINT         NULL,
                );

                CREATE TABLE [app].[SyncAppSources] (
                    [OldAppSourceID]  BIGINT         PRIMARY KEY,
                    [AppSourceID] BIGINT         NULL,
                );

                CREATE TABLE [app].[SyncPaymentModes] (
                    [OldPaymentModeID]  BIGINT         PRIMARY KEY,
                    [PaymentModeID] BIGINT         NULL,
                );

                CREATE TABLE [app].[SyncServices] (
                    [OldServiceID]  BIGINT         PRIMARY KEY,
                    [ServiceID] BIGINT         NULL,
                );

                CREATE TABLE [app].[SyncUnits] (
                    [OldUnitID]  BIGINT         PRIMARY KEY,
                    [UnitID] BIGINT         NULL,
                );

                                 
                ALTER TABLE [app].[PurchaseBills]
                ALTER COLUMN AuditedByUserID BIGINT NULL;
                
                              
                ALTER TABLE [app].[Orders]
                ALTER COLUMN OrderTakerID BIGINT NULL;

                              
                -- app.RolesAndPermissions
                CREATE TABLE app.RolesAndPermissions (
                    [Role] VARCHAR(255) NOT NULL,
                    [ClaimType] VARCHAR(255) NOT NULL,
                    [ClaimValue] VARCHAR(255) NOT NULL,
                );
                
                CREATE CLUSTERED INDEX CX_Claims_Role
                ON app.RolesAndPermissions ([Role]);


                INSERT INTO app.RolesAndPermissions (Role, ClaimType, ClaimValue)
                VALUES  ('SuperAdmin', 'Permission', 'AccountPaymentMode_Create'),
                        ('SuperAdmin', 'Permission', 'AccountPaymentMode_Delete'),
                        ('SuperAdmin', 'Permission', 'AccountPaymentMode_Get'),
                        ('SuperAdmin', 'Permission', 'AccountPaymentMode_GetAccountList'),
                        ('SuperAdmin', 'Permission', 'AccountPaymentMode_GetList'),
                        ('SuperAdmin', 'Permission', 'AccountPaymentMode_Update'),
                        ('SuperAdmin', 'Permission', 'Account_Create'),
                        ('SuperAdmin', 'Permission', 'Account_Delete'),
                        ('SuperAdmin', 'Permission', 'Account_Get'),
                        ('SuperAdmin', 'Permission', 'Account_GetList'),
                        ('SuperAdmin', 'Permission', 'Account_Update'),
                        ('SuperAdmin', 'Permission', 'AddOn_Create'),
                        ('SuperAdmin', 'Permission', 'AddOn_Delete'),
                        ('SuperAdmin', 'Permission', 'AddOn_Get'),
                        ('SuperAdmin', 'Permission', 'AddOn_GetList'),
                        ('SuperAdmin', 'Permission', 'AddOn_Update'),
                        ('SuperAdmin', 'Permission', 'Amenity_Create'),
                        ('SuperAdmin', 'Permission', 'Amenity_Delete'),
                        ('SuperAdmin', 'Permission', 'Amenity_Get'),
                        ('SuperAdmin', 'Permission', 'Amenity_GetList'),
                        ('SuperAdmin', 'Permission', 'Amenity_Update'),
                        ('SuperAdmin', 'Permission', 'AppSource_Create'),
                        ('SuperAdmin', 'Permission', 'AppSource_Delete'),
                        ('SuperAdmin', 'Permission', 'AppSource_Get'),
                        ('SuperAdmin', 'Permission', 'AppSource_GetList'),
                        ('SuperAdmin', 'Permission', 'AppSource_Update'),
                        ('SuperAdmin', 'Permission', 'Authentication_Create'),
                        ('SuperAdmin', 'Permission', 'Authentication_Update'),
                        ('SuperAdmin', 'Permission', 'Bay_Create'),
                        ('SuperAdmin', 'Permission', 'Bay_Delete'),
                        ('SuperAdmin', 'Permission', 'Bay_Get'),
                        ('SuperAdmin', 'Permission', 'Bay_GetList'),
                        ('SuperAdmin', 'Permission', 'Bay_Update'),
                        ('SuperAdmin', 'Permission', 'Car_Create'),
                        ('SuperAdmin', 'Permission', 'Car_Delete'),
                        ('SuperAdmin', 'Permission', 'Car_Get'),
                        ('SuperAdmin', 'Permission', 'Car_GetList'),
                        ('SuperAdmin', 'Permission', 'Car_Update'),
                        ('SuperAdmin', 'Permission', 'Category_Create'),
                        ('SuperAdmin', 'Permission', 'Category_Delete'),
                        ('SuperAdmin', 'Permission', 'Category_Get'),
                        ('SuperAdmin', 'Permission', 'Category_GetList'),
                        ('SuperAdmin', 'Permission', 'Category_Update'),
                        ('SuperAdmin', 'Permission', 'City_Get'),
                        ('SuperAdmin', 'Permission', 'City_GetList'),
                        ('SuperAdmin', 'Permission', 'CompanyClient_Create'),
                        ('SuperAdmin', 'Permission', 'CompanyClient_Delete'),
                        ('SuperAdmin', 'Permission', 'CompanyClient_Get'),
                        ('SuperAdmin', 'Permission', 'CompanyClient_GetList'),
                        ('SuperAdmin', 'Permission', 'CompanyClient_Update'),
                        ('SuperAdmin', 'Permission', 'CompanyInvoice_Read'),
                        ('SuperAdmin', 'Permission', 'Country_Get'),
                        ('SuperAdmin', 'Permission', 'Country_GetList'),
                        ('SuperAdmin', 'Permission', 'CreditCustomer_GetInvoices'),
                        ('SuperAdmin', 'Permission', 'CreditCustomer_GetList'),
                        ('SuperAdmin', 'Permission', 'CustomerPayment_GetStatement'),
                        ('SuperAdmin', 'Permission', 'CustomerPayment_Record'),
                        ('SuperAdmin', 'Permission', 'Customer_Create'),
                        ('SuperAdmin', 'Permission', 'Customer_Delete'),
                        ('SuperAdmin', 'Permission', 'Customer_Get'),
                        ('SuperAdmin', 'Permission', 'Customer_GetList'),
                        ('SuperAdmin', 'Permission', 'Customer_Update'),
                        ('SuperAdmin', 'Permission', 'File_Create'),
                        ('SuperAdmin', 'Permission', 'File_Get'),
                        ('SuperAdmin', 'Permission', 'Item_Create'),
                        ('SuperAdmin', 'Permission', 'Item_Delete'),
                        ('SuperAdmin', 'Permission', 'Item_Get'),
                        ('SuperAdmin', 'Permission', 'Item_GetList'),
                        ('SuperAdmin', 'Permission', 'Item_Update'),
                        ('SuperAdmin', 'Permission', 'Landmark_Create'),
                        ('SuperAdmin', 'Permission', 'Landmark_Delete'),
                        ('SuperAdmin', 'Permission', 'Landmark_Get'),
                        ('SuperAdmin', 'Permission', 'Landmark_GetList'),
                        ('SuperAdmin', 'Permission', 'Landmark_Update'),
                        ('SuperAdmin', 'Permission', 'LocationSetting_Create'),
                        ('SuperAdmin', 'Permission', 'LocationSetting_Delete'),
                        ('SuperAdmin', 'Permission', 'LocationSetting_Get'),
                        ('SuperAdmin', 'Permission', 'LocationSetting_GetList'),
                        ('SuperAdmin', 'Permission', 'LocationSetting_Update'),
                        ('SuperAdmin', 'Permission', 'Location_Create'),
                        ('SuperAdmin', 'Permission', 'Location_Delete'),
                        ('SuperAdmin', 'Permission', 'Location_Get'),
                        ('SuperAdmin', 'Permission', 'Location_GetList'),
                        ('SuperAdmin', 'Permission', 'Location_Update'),
                        ('SuperAdmin', 'Permission', 'Make_Create'),
                        ('SuperAdmin', 'Permission', 'Make_Delete'),
                        ('SuperAdmin', 'Permission', 'Make_Get'),
                        ('SuperAdmin', 'Permission', 'Make_GetList'),
                        ('SuperAdmin', 'Permission', 'Make_Update'),
                        ('SuperAdmin', 'Permission', 'Model_Create'),
                        ('SuperAdmin', 'Permission', 'Model_Delete'),
                        ('SuperAdmin', 'Permission', 'Model_Get'),
                        ('SuperAdmin', 'Permission', 'Model_GetList'),
                        ('SuperAdmin', 'Permission', 'Model_Update'),
                        ('SuperAdmin', 'Permission', 'Notification_Create'),
                        ('SuperAdmin', 'Permission', 'Notification_Delete'),
                        ('SuperAdmin', 'Permission', 'Notification_Get'),
                        ('SuperAdmin', 'Permission', 'Notification_GetList'),
                        ('SuperAdmin', 'Permission', 'Notification_GetUnreadList'),
                        ('SuperAdmin', 'Permission', 'Notification_Update'),
                        ('SuperAdmin', 'Permission', 'OrderNote_Create'),
                        ('SuperAdmin', 'Permission', 'OrderNote_Delete'),
                        ('SuperAdmin', 'Permission', 'OrderNote_Get'),
                        ('SuperAdmin', 'Permission', 'OrderNote_GetList'),
                        ('SuperAdmin', 'Permission', 'OrderNote_GetOrderList'),
                        ('SuperAdmin', 'Permission', 'OrderNote_Update'),
                        ('SuperAdmin', 'Permission', 'Order_Create'),
                        ('SuperAdmin', 'Permission', 'Package_Create'),
                        ('SuperAdmin', 'Permission', 'Package_Delete'),
                        ('SuperAdmin', 'Permission', 'Package_Get'),
                        ('SuperAdmin', 'Permission', 'Package_GetList'),
                        ('SuperAdmin', 'Permission', 'Package_Update'),
                        ('SuperAdmin', 'Permission', 'PaymentMode_Create'),
                        ('SuperAdmin', 'Permission', 'PaymentMode_Delete'),
                        ('SuperAdmin', 'Permission', 'PaymentMode_Get'),
                        ('SuperAdmin', 'Permission', 'PaymentMode_GetList'),
                        ('SuperAdmin', 'Permission', 'PaymentMode_Update'),
                        ('SuperAdmin', 'Permission', 'Permission_GetList'),
                        ('SuperAdmin', 'Permission', 'Product_GetList'),
                        ('SuperAdmin', 'Permission', 'PurchaseBill_Create'),
                        ('SuperAdmin', 'Permission', 'PurchaseBills_Get'),
                        ('SuperAdmin', 'Permission', 'PurchaseBills_GetList'),
                        ('SuperAdmin', 'Permission', 'PurchaseOrder_Approve'),
                        ('SuperAdmin', 'Permission', 'PurchaseOrder_Create'),
                        ('SuperAdmin', 'Permission', 'PurchaseOrder_Delete'),
                        ('SuperAdmin', 'Permission', 'PurchaseOrder_Get'),
                        ('SuperAdmin', 'Permission', 'PurchaseOrder_Submit'),
                        ('SuperAdmin', 'Permission', 'PurchaseOrder_Update'),
                        ('SuperAdmin', 'Permission', 'PurchaseOrders_Get'),
                        ('SuperAdmin', 'Permission', 'Quotation_Create'),
                        ('SuperAdmin', 'Permission', 'Quotation_Delete'),
                        ('SuperAdmin', 'Permission', 'Quotation_Get'),
                        ('SuperAdmin', 'Permission', 'Quotation_GetList'),
                        ('SuperAdmin', 'Permission', 'Quotation_Update'),
                        ('SuperAdmin', 'Permission', 'Reconciliations_Audit'),
                        ('SuperAdmin', 'Permission', 'Reconciliations_Create'),
                        ('SuperAdmin', 'Permission', 'Reconciliations_Get'),
                        ('SuperAdmin', 'Permission', 'Reconciliations_GetList'),
                        ('SuperAdmin', 'Permission', 'Reconciliations_Submit'),
                        ('SuperAdmin', 'Permission', 'Reconciliations_Update'),
                        ('SuperAdmin', 'Permission', 'RefundPolicy_Create'),
                        ('SuperAdmin', 'Permission', 'RefundPolicy_Delete'),
                        ('SuperAdmin', 'Permission', 'RefundPolicy_GetById'),
                        ('SuperAdmin', 'Permission', 'RefundPolicy_GetEffective'),
                        ('SuperAdmin', 'Permission', 'RefundPolicy_GetList'),
                        ('SuperAdmin', 'Permission', 'RefundPolicy_Update'),
                        ('SuperAdmin', 'Permission', 'Refund_Calculate'),
                        ('SuperAdmin', 'Permission', 'Refund_GetHistory'),
                        ('SuperAdmin', 'Permission', 'Refund_Process'),
                        ('SuperAdmin', 'Permission', 'Report_Get'),
                        ('SuperAdmin', 'Permission', 'Role_Create'),
                        ('SuperAdmin', 'Permission', 'Role_Delete'),
                        ('SuperAdmin', 'Permission', 'Role_Get'),
                        ('SuperAdmin', 'Permission', 'Role_GetList'),
                        ('SuperAdmin', 'Permission', 'Role_Update'),
                        ('SuperAdmin', 'Permission', 'Service_Create'),
                        ('SuperAdmin', 'Permission', 'Service_Delete'),
                        ('SuperAdmin', 'Permission', 'Service_GetList'),
                        ('SuperAdmin', 'Permission', 'Service_Update'),
                        ('SuperAdmin', 'Permission', 'StockRequest_Approve'),
                        ('SuperAdmin', 'Permission', 'StockRequest_Create'),
                        ('SuperAdmin', 'Permission', 'StockTransfer_Create'),
                        ('SuperAdmin', 'Permission', 'StockTransfer_Get'),
                        ('SuperAdmin', 'Permission', 'StockTransfer_GetList'),
                        ('SuperAdmin', 'Permission', 'StockTransfer_GetListByWarehouse'),
                        ('SuperAdmin', 'Permission', 'StockTransfer_Receive'),
                        ('SuperAdmin', 'Permission', 'Stock_Get'),
                        ('SuperAdmin', 'Permission', 'Stocks_Get'),
                        ('SuperAdmin', 'Permission', 'SubscriptionAddOn_Create'),
                        ('SuperAdmin', 'Permission', 'SubscriptionAddOn_Delete'),
                        ('SuperAdmin', 'Permission', 'SubscriptionAddOn_Get'),
                        ('SuperAdmin', 'Permission', 'SubscriptionAddOn_GetList'),
                        ('SuperAdmin', 'Permission', 'SubscriptionAddOn_Update'),
                        ('SuperAdmin', 'Permission', 'Subscription_Create'),
                        ('SuperAdmin', 'Permission', 'Subscription_Delete'),
                        ('SuperAdmin', 'Permission', 'Subscription_Get'),
                        ('SuperAdmin', 'Permission', 'Subscription_GetList'),
                        ('SuperAdmin', 'Permission', 'Subscription_Update'),
                        ('SuperAdmin', 'Permission', 'Supplier_Create'),
                        ('SuperAdmin', 'Permission', 'Supplier_Delete'),
                        ('SuperAdmin', 'Permission', 'Supplier_Get'),
                        ('SuperAdmin', 'Permission', 'Supplier_GetList'),
                        ('SuperAdmin', 'Permission', 'Supplier_Update'),
                        ('SuperAdmin', 'Permission', 'Tax_Create'),
                        ('SuperAdmin', 'Permission', 'Tax_Delete'),
                        ('SuperAdmin', 'Permission', 'Tax_Get'),
                        ('SuperAdmin', 'Permission', 'Tax_GetList'),
                        ('SuperAdmin', 'Permission', 'Tax_Update'),
                        ('SuperAdmin', 'Permission', 'Technician_GetList'),
                        ('SuperAdmin', 'Permission', 'Terminal_Create'),
                        ('SuperAdmin', 'Permission', 'Terminal_Delete'),
                        ('SuperAdmin', 'Permission', 'Terminal_Get'),
                        ('SuperAdmin', 'Permission', 'Terminal_GetList'),
                        ('SuperAdmin', 'Permission', 'Terminal_Update'),
                        ('SuperAdmin', 'Permission', 'User_Create'),
                        ('SuperAdmin', 'Permission', 'User_Delete'),
                        ('SuperAdmin', 'Permission', 'User_Get'),
                        ('SuperAdmin', 'Permission', 'User_GetList'),
                        ('SuperAdmin', 'Permission', 'User_Update'),
                        ('SuperAdmin', 'Permission', 'Version_Get'),
                        ('SuperAdmin', 'Permission', 'Warehouse_Create'),
                        ('SuperAdmin', 'Permission', 'Warehouse_Delete'),
                        ('SuperAdmin', 'Permission', 'Warehouse_Get'),
                        ('SuperAdmin', 'Permission', 'Warehouse_GetList'),
                        ('SuperAdmin', 'Permission', 'Warehouse_Update'),
                        ('SuperAdmin', 'Permission', 'Webhook_Create'),
                        ('SuperAdmin', 'Permission', 'Webhook_Get'),
                        ('SuperAdmin', 'Permission', 'Webhook_GetList'),
                        ('SuperAdmin', 'Permission', 'Webhook_TestUpdate'),
                        ('SuperAdmin', 'Permission', 'Webhook_Update'),
                        ('SuperAdmin', 'Permission', 'Zatca_Submit_Invoice'),

                        ('AccountsManager', 'Permission', 'AccountPaymentMode_Create'),
                        ('AccountsManager', 'Permission', 'AccountPaymentMode_Delete'),
                        ('AccountsManager', 'Permission', 'AccountPaymentMode_Get'),
                        ('AccountsManager', 'Permission', 'AccountPaymentMode_GetAccountList'),
                        ('AccountsManager', 'Permission', 'AccountPaymentMode_GetList'),
                        ('AccountsManager', 'Permission', 'AccountPaymentMode_Update'),
                        ('AccountsManager', 'Permission', 'Account_Create'),
                        ('AccountsManager', 'Permission', 'Account_Delete'),
                        ('AccountsManager', 'Permission', 'Account_Get'),
                        ('AccountsManager', 'Permission', 'Account_GetList'),
                        ('AccountsManager', 'Permission', 'Account_Update'),
                        ('AccountsManager', 'Permission', 'AddOn_Create'),
                        ('AccountsManager', 'Permission', 'AddOn_Delete'),
                        ('AccountsManager', 'Permission', 'AddOn_Get'),
                        ('AccountsManager', 'Permission', 'AddOn_GetList'),
                        ('AccountsManager', 'Permission', 'AddOn_Update'),
                        ('AccountsManager', 'Permission', 'Amenity_Create'),
                        ('AccountsManager', 'Permission', 'Amenity_Delete'),
                        ('AccountsManager', 'Permission', 'Amenity_Get'),
                        ('AccountsManager', 'Permission', 'Amenity_GetList'),
                        ('AccountsManager', 'Permission', 'Amenity_Update'),
                        ('AccountsManager', 'Permission', 'AppSource_Create'),
                        ('AccountsManager', 'Permission', 'AppSource_Delete'),
                        ('AccountsManager', 'Permission', 'AppSource_Get'),
                        ('AccountsManager', 'Permission', 'AppSource_GetList'),
                        ('AccountsManager', 'Permission', 'AppSource_Update'),
                        ('AccountsManager', 'Permission', 'Authentication_Create'),
                        ('AccountsManager', 'Permission', 'Authentication_Update'),
                        ('AccountsManager', 'Permission', 'Bay_Create'),
                        ('AccountsManager', 'Permission', 'Bay_Delete'),
                        ('AccountsManager', 'Permission', 'Bay_Get'),
                        ('AccountsManager', 'Permission', 'Bay_GetList'),
                        ('AccountsManager', 'Permission', 'Bay_Update'),
                        ('AccountsManager', 'Permission', 'Car_Create'),
                        ('AccountsManager', 'Permission', 'Car_Delete'),
                        ('AccountsManager', 'Permission', 'Car_Get'),
                        ('AccountsManager', 'Permission', 'Car_GetList'),
                        ('AccountsManager', 'Permission', 'Car_Update'),
                        ('AccountsManager', 'Permission', 'Category_Create'),
                        ('AccountsManager', 'Permission', 'Category_Delete'),
                        ('AccountsManager', 'Permission', 'Category_Get'),
                        ('AccountsManager', 'Permission', 'Category_GetList'),
                        ('AccountsManager', 'Permission', 'Category_Update'),
                        ('AccountsManager', 'Permission', 'City_Get'),
                        ('AccountsManager', 'Permission', 'City_GetList'),
                        ('AccountsManager', 'Permission', 'CompanyClient_Create'),
                        ('AccountsManager', 'Permission', 'CompanyClient_Delete'),
                        ('AccountsManager', 'Permission', 'CompanyClient_Get'),
                        ('AccountsManager', 'Permission', 'CompanyClient_GetList'),
                        ('AccountsManager', 'Permission', 'CompanyClient_Update'),
                        ('AccountsManager', 'Permission', 'CompanyInvoice_Read'),
                        ('AccountsManager', 'Permission', 'Country_Get'),
                        ('AccountsManager', 'Permission', 'Country_GetList'),
                        ('AccountsManager', 'Permission', 'CreditCustomer_GetInvoices'),
                        ('AccountsManager', 'Permission', 'CreditCustomer_GetList'),
                        ('AccountsManager', 'Permission', 'CustomerPayment_GetStatement'),
                        ('AccountsManager', 'Permission', 'CustomerPayment_Record'),
                        ('AccountsManager', 'Permission', 'Customer_Create'),
                        ('AccountsManager', 'Permission', 'Customer_Delete'),
                        ('AccountsManager', 'Permission', 'Customer_Get'),
                        ('AccountsManager', 'Permission', 'Customer_GetList'),
                        ('AccountsManager', 'Permission', 'Customer_Update'),
                        ('AccountsManager', 'Permission', 'File_Create'),
                        ('AccountsManager', 'Permission', 'File_Get'),
                        ('AccountsManager', 'Permission', 'Item_Create'),
                        ('AccountsManager', 'Permission', 'Item_Delete'),
                        ('AccountsManager', 'Permission', 'Item_Get'),
                        ('AccountsManager', 'Permission', 'Item_GetList'),
                        ('AccountsManager', 'Permission', 'Item_Update'),
                        ('AccountsManager', 'Permission', 'Landmark_Create'),
                        ('AccountsManager', 'Permission', 'Landmark_Delete'),
                        ('AccountsManager', 'Permission', 'Landmark_Get'),
                        ('AccountsManager', 'Permission', 'Landmark_GetList'),
                        ('AccountsManager', 'Permission', 'Landmark_Update'),
                        ('AccountsManager', 'Permission', 'LocationSetting_Create'),
                        ('AccountsManager', 'Permission', 'LocationSetting_Delete'),
                        ('AccountsManager', 'Permission', 'LocationSetting_Get'),
                        ('AccountsManager', 'Permission', 'LocationSetting_GetList'),
                        ('AccountsManager', 'Permission', 'LocationSetting_Update'),
                        ('AccountsManager', 'Permission', 'Location_Create'),
                        ('AccountsManager', 'Permission', 'Location_Delete'),
                        ('AccountsManager', 'Permission', 'Location_Get'),
                        ('AccountsManager', 'Permission', 'Location_GetList'),
                        ('AccountsManager', 'Permission', 'Location_Update'),
                        ('AccountsManager', 'Permission', 'Make_Create'),
                        ('AccountsManager', 'Permission', 'Make_Delete'),
                        ('AccountsManager', 'Permission', 'Make_Get'),
                        ('AccountsManager', 'Permission', 'Make_GetList'),
                        ('AccountsManager', 'Permission', 'Make_Update'),
                        ('AccountsManager', 'Permission', 'Model_Create'),
                        ('AccountsManager', 'Permission', 'Model_Delete'),
                        ('AccountsManager', 'Permission', 'Model_Get'),
                        ('AccountsManager', 'Permission', 'Model_GetList'),
                        ('AccountsManager', 'Permission', 'Model_Update'),
                        ('AccountsManager', 'Permission', 'Notification_Create'),
                        ('AccountsManager', 'Permission', 'Notification_Delete'),
                        ('AccountsManager', 'Permission', 'Notification_Get'),
                        ('AccountsManager', 'Permission', 'Notification_GetList'),
                        ('AccountsManager', 'Permission', 'Notification_GetUnreadList'),
                        ('AccountsManager', 'Permission', 'Notification_Update'),
                        ('AccountsManager', 'Permission', 'OrderNote_Create'),
                        ('AccountsManager', 'Permission', 'OrderNote_Delete'),
                        ('AccountsManager', 'Permission', 'OrderNote_Get'),
                        ('AccountsManager', 'Permission', 'OrderNote_GetList'),
                        ('AccountsManager', 'Permission', 'OrderNote_GetOrderList'),
                        ('AccountsManager', 'Permission', 'OrderNote_Update'),
                        ('AccountsManager', 'Permission', 'Order_Create'),
                        ('AccountsManager', 'Permission', 'Package_Create'),
                        ('AccountsManager', 'Permission', 'Package_Delete'),
                        ('AccountsManager', 'Permission', 'Package_Get'),
                        ('AccountsManager', 'Permission', 'Package_GetList'),
                        ('AccountsManager', 'Permission', 'Package_Update'),
                        ('AccountsManager', 'Permission', 'PaymentMode_Create'),
                        ('AccountsManager', 'Permission', 'PaymentMode_Delete'),
                        ('AccountsManager', 'Permission', 'PaymentMode_Get'),
                        ('AccountsManager', 'Permission', 'PaymentMode_GetList'),
                        ('AccountsManager', 'Permission', 'PaymentMode_Update'),
                        ('AccountsManager', 'Permission', 'Permission_GetList'),
                        ('AccountsManager', 'Permission', 'Product_GetList'),
                        ('AccountsManager', 'Permission', 'PurchaseBill_Create'),
                        ('AccountsManager', 'Permission', 'PurchaseBills_Get'),
                        ('AccountsManager', 'Permission', 'PurchaseBills_GetList'),
                        ('AccountsManager', 'Permission', 'PurchaseOrder_Approve'),
                        ('AccountsManager', 'Permission', 'PurchaseOrder_Create'),
                        ('AccountsManager', 'Permission', 'PurchaseOrder_Delete'),
                        ('AccountsManager', 'Permission', 'PurchaseOrder_Get'),
                        ('AccountsManager', 'Permission', 'PurchaseOrder_Submit'),
                        ('AccountsManager', 'Permission', 'PurchaseOrder_Update'),
                        ('AccountsManager', 'Permission', 'PurchaseOrders_Get'),
                        ('AccountsManager', 'Permission', 'Quotation_Create'),
                        ('AccountsManager', 'Permission', 'Quotation_Delete'),
                        ('AccountsManager', 'Permission', 'Quotation_Get'),
                        ('AccountsManager', 'Permission', 'Quotation_GetList'),
                        ('AccountsManager', 'Permission', 'Quotation_Update'),
                        ('AccountsManager', 'Permission', 'Reconciliations_Audit'),
                        ('AccountsManager', 'Permission', 'Reconciliations_Create'),
                        ('AccountsManager', 'Permission', 'Reconciliations_Get'),
                        ('AccountsManager', 'Permission', 'Reconciliations_GetList'),
                        ('AccountsManager', 'Permission', 'Reconciliations_Submit'),
                        ('AccountsManager', 'Permission', 'Reconciliations_Update'),
                        ('AccountsManager', 'Permission', 'RefundPolicy_Create'),
                        ('AccountsManager', 'Permission', 'RefundPolicy_Delete'),
                        ('AccountsManager', 'Permission', 'RefundPolicy_GetById'),
                        ('AccountsManager', 'Permission', 'RefundPolicy_GetEffective'),
                        ('AccountsManager', 'Permission', 'RefundPolicy_GetList'),
                        ('AccountsManager', 'Permission', 'RefundPolicy_Update'),
                        ('AccountsManager', 'Permission', 'Refund_Calculate'),
                        ('AccountsManager', 'Permission', 'Refund_GetHistory'),
                        ('AccountsManager', 'Permission', 'Refund_Process'),
                        ('AccountsManager', 'Permission', 'Report_Get'),
                        ('AccountsManager', 'Permission', 'Role_Create'),
                        ('AccountsManager', 'Permission', 'Role_Delete'),
                        ('AccountsManager', 'Permission', 'Role_Get'),
                        ('AccountsManager', 'Permission', 'Role_GetList'),
                        ('AccountsManager', 'Permission', 'Role_Update'),
                        ('AccountsManager', 'Permission', 'Service_Create'),
                        ('AccountsManager', 'Permission', 'Service_Delete'),
                        ('AccountsManager', 'Permission', 'Service_GetList'),
                        ('AccountsManager', 'Permission', 'Service_Update'),
                        ('AccountsManager', 'Permission', 'StockRequest_Approve'),
                        ('AccountsManager', 'Permission', 'StockRequest_Create'),
                        ('AccountsManager', 'Permission', 'StockTransfer_Create'),
                        ('AccountsManager', 'Permission', 'StockTransfer_Get'),
                        ('AccountsManager', 'Permission', 'StockTransfer_GetList'),
                        ('AccountsManager', 'Permission', 'StockTransfer_GetListByWarehouse'),
                        ('AccountsManager', 'Permission', 'StockTransfer_Receive'),
                        ('AccountsManager', 'Permission', 'Stock_Get'),
                        ('AccountsManager', 'Permission', 'Stocks_Get'),
                        ('AccountsManager', 'Permission', 'SubscriptionAddOn_Create'),
                        ('AccountsManager', 'Permission', 'SubscriptionAddOn_Delete'),
                        ('AccountsManager', 'Permission', 'SubscriptionAddOn_Get'),
                        ('AccountsManager', 'Permission', 'SubscriptionAddOn_GetList'),
                        ('AccountsManager', 'Permission', 'SubscriptionAddOn_Update'),
                        ('AccountsManager', 'Permission', 'Subscription_Create'),
                        ('AccountsManager', 'Permission', 'Subscription_Delete'),
                        ('AccountsManager', 'Permission', 'Subscription_Get'),
                        ('AccountsManager', 'Permission', 'Subscription_GetList'),
                        ('AccountsManager', 'Permission', 'Subscription_Update'),
                        ('AccountsManager', 'Permission', 'Supplier_Create'),
                        ('AccountsManager', 'Permission', 'Supplier_Delete'),
                        ('AccountsManager', 'Permission', 'Supplier_Get'),
                        ('AccountsManager', 'Permission', 'Supplier_GetList'),
                        ('AccountsManager', 'Permission', 'Supplier_Update'),
                        ('AccountsManager', 'Permission', 'Tax_Create'),
                        ('AccountsManager', 'Permission', 'Tax_Delete'),
                        ('AccountsManager', 'Permission', 'Tax_Get'),
                        ('AccountsManager', 'Permission', 'Tax_GetList'),
                        ('AccountsManager', 'Permission', 'Tax_Update'),
                        ('AccountsManager', 'Permission', 'Technician_GetList'),
                        ('AccountsManager', 'Permission', 'Terminal_Create'),
                        ('AccountsManager', 'Permission', 'Terminal_Delete'),
                        ('AccountsManager', 'Permission', 'Terminal_Get'),
                        ('AccountsManager', 'Permission', 'Terminal_GetList'),
                        ('AccountsManager', 'Permission', 'Terminal_Update'),
                        ('AccountsManager', 'Permission', 'User_Create'),
                        ('AccountsManager', 'Permission', 'User_Delete'),
                        ('AccountsManager', 'Permission', 'User_Get'),
                        ('AccountsManager', 'Permission', 'User_GetList'),
                        ('AccountsManager', 'Permission', 'User_Update'),
                        ('AccountsManager', 'Permission', 'Version_Get'),
                        ('AccountsManager', 'Permission', 'Warehouse_Create'),
                        ('AccountsManager', 'Permission', 'Warehouse_Delete'),
                        ('AccountsManager', 'Permission', 'Warehouse_Get'),
                        ('AccountsManager', 'Permission', 'Warehouse_GetList'),
                        ('AccountsManager', 'Permission', 'Warehouse_Update'),
                        ('AccountsManager', 'Permission', 'Webhook_Create'),
                        ('AccountsManager', 'Permission', 'Webhook_Get'),
                        ('AccountsManager', 'Permission', 'Webhook_GetList'),
                        ('AccountsManager', 'Permission', 'Webhook_TestUpdate'),
                        ('AccountsManager', 'Permission', 'Webhook_Update'),
                        ('AccountsManager', 'Permission', 'Zatca_Submit_Invoice'),

                        ('AccountManager', 'Permission', 'AccountPaymentMode_Create'),
                        ('AccountManager', 'Permission', 'AccountPaymentMode_Get'),
                        ('AccountManager', 'Permission', 'AccountPaymentMode_Update'),
                        ('AccountManager', 'Permission', 'Account_Create'),
                        ('AccountManager', 'Permission', 'Account_Get'),
                        ('AccountManager', 'Permission', 'Account_GetList'),
                        ('AccountManager', 'Permission', 'Account_Update'),
                        ('AccountManager', 'Permission', 'AddOn_Create'),
                        ('AccountManager', 'Permission', 'AddOn_Get'),
                        ('AccountManager', 'Permission', 'AddOn_Update'),
                        ('AccountManager', 'Permission', 'Amenity_Create'),
                        ('AccountManager', 'Permission', 'Amenity_Get'),
                        ('AccountManager', 'Permission', 'Amenity_Update'),
                        ('AccountManager', 'Permission', 'AppSource_Create'),
                        ('AccountManager', 'Permission', 'AppSource_Get'),
                        ('AccountManager', 'Permission', 'AppSource_Update'),
                        ('AccountManager', 'Permission', 'Authentication_Create'),
                        ('AccountManager', 'Permission', 'Authentication_Update'),
                        ('AccountManager', 'Permission', 'Bay_Create'),
                        ('AccountManager', 'Permission', 'Bay_Get'),
                        ('AccountManager', 'Permission', 'Bay_Update'),
                        ('AccountManager', 'Permission', 'Car_Create'),
                        ('AccountManager', 'Permission', 'Car_Get'),
                        ('AccountManager', 'Permission', 'Car_Update'),
                        ('AccountManager', 'Permission', 'Category_Create'),
                        ('AccountManager', 'Permission', 'Category_Get'),
                        ('AccountManager', 'Permission', 'Category_Update'),
                        ('AccountManager', 'Permission', 'City_Get'),
                        ('AccountManager', 'Permission', 'CompanyClient_Create'),
                        ('AccountManager', 'Permission', 'CompanyClient_Get'),
                        ('AccountManager', 'Permission', 'CompanyClient_Update'),
                        ('AccountManager', 'Permission', 'CompanyInvoice_Read'),
                        ('AccountManager', 'Permission', 'Country_Get'),
                        ('AccountManager', 'Permission', 'CreditCustomer_GetInvoices'),
                        ('AccountManager', 'Permission', 'CustomerPayment_Record'),
                        ('AccountManager', 'Permission', 'Customer_Create'),
                        ('AccountManager', 'Permission', 'Customer_Get'),
                        ('AccountManager', 'Permission', 'Customer_Update'),
                        ('AccountManager', 'Permission', 'File_Create'),
                        ('AccountManager', 'Permission', 'File_Get'),
                        ('AccountManager', 'Permission', 'Item_Create'),
                        ('AccountManager', 'Permission', 'Item_Get'),
                        ('AccountManager', 'Permission', 'Item_Update'),
                        ('AccountManager', 'Permission', 'Landmark_Create'),
                        ('AccountManager', 'Permission', 'Landmark_Get'),
                        ('AccountManager', 'Permission', 'Landmark_Update'),
                        ('AccountManager', 'Permission', 'LocationSetting_Create'),
                        ('AccountManager', 'Permission', 'LocationSetting_Get'),
                        ('AccountManager', 'Permission', 'LocationSetting_Update'),
                        ('AccountManager', 'Permission', 'Location_Create'),
                        ('AccountManager', 'Permission', 'Location_Get'),
                        ('AccountManager', 'Permission', 'Location_GetList'),
                        ('AccountManager', 'Permission', 'Location_Update'),
                        ('AccountManager', 'Permission', 'Make_Create'),
                        ('AccountManager', 'Permission', 'Make_Get'),
                        ('AccountManager', 'Permission', 'Make_GetList'),
                        ('AccountManager', 'Permission', 'Make_Update'),
                        ('AccountManager', 'Permission', 'Model_Create'),
                        ('AccountManager', 'Permission', 'Model_Get'),
                        ('AccountManager', 'Permission', 'Model_Update'),
                        ('AccountManager', 'Permission', 'Notification_Create'),
                        ('AccountManager', 'Permission', 'Notification_Get'),
                        ('AccountManager', 'Permission', 'Notification_GetUnreadList'),
                        ('AccountManager', 'Permission', 'Notification_Update'),
                        ('AccountManager', 'Permission', 'OrderNote_Create'),
                        ('AccountManager', 'Permission', 'OrderNote_Get'),
                        ('AccountManager', 'Permission', 'OrderNote_GetOrderList'),
                        ('AccountManager', 'Permission', 'OrderNote_Update'),
                        ('AccountManager', 'Permission', 'Order_Create'),
                        ('AccountManager', 'Permission', 'Package_Create'),
                        ('AccountManager', 'Permission', 'Package_Get'),
                        ('AccountManager', 'Permission', 'Package_Update'),
                        ('AccountManager', 'Permission', 'PaymentMode_Create'),
                        ('AccountManager', 'Permission', 'PaymentMode_Get'),
                        ('AccountManager', 'Permission', 'PaymentMode_Update'),
                        ('AccountManager', 'Permission', 'PurchaseBill_Create'),
                        ('AccountManager', 'Permission', 'PurchaseBills_Get'),
                        ('AccountManager', 'Permission', 'PurchaseOrder_Approve'),
                        ('AccountManager', 'Permission', 'PurchaseOrder_Create'),
                        ('AccountManager', 'Permission', 'PurchaseOrder_Get'),
                        ('AccountManager', 'Permission', 'PurchaseOrder_Submit'),
                        ('AccountManager', 'Permission', 'PurchaseOrder_Update'),
                        ('AccountManager', 'Permission', 'PurchaseOrders_Get'),
                        ('AccountManager', 'Permission', 'Quotation_Create'),
                        ('AccountManager', 'Permission', 'Quotation_Get'),
                        ('AccountManager', 'Permission', 'Quotation_Update'),
                        ('AccountManager', 'Permission', 'Reconciliations_Audit'),
                        ('AccountManager', 'Permission', 'Reconciliations_Create'),
                        ('AccountManager', 'Permission', 'Reconciliations_Get'),
                        ('AccountManager', 'Permission', 'Reconciliations_Submit'),
                        ('AccountManager', 'Permission', 'Reconciliations_Update'),
                        ('AccountManager', 'Permission', 'RefundPolicy_Create'),
                        ('AccountManager', 'Permission', 'RefundPolicy_GetById'),
                        ('AccountManager', 'Permission', 'RefundPolicy_GetEffective'),
                        ('AccountManager', 'Permission', 'Refund_GetHistory'),
                        ('AccountManager', 'Permission', 'Report_Get'),
                        ('AccountManager', 'Permission', 'Role_Create'),
                        ('AccountManager', 'Permission', 'Role_Get'),
                        ('AccountManager', 'Permission', 'Service_Create'),
                        ('AccountManager', 'Permission', 'Service_Update'),
                        ('AccountManager', 'Permission', 'StockRequest_Approve'),
                        ('AccountManager', 'Permission', 'StockRequest_Create'),
                        ('AccountManager', 'Permission', 'StockTransfer_Create'),
                        ('AccountManager', 'Permission', 'StockTransfer_Get'),
                        ('AccountManager', 'Permission', 'StockTransfer_Receive'),
                        ('AccountManager', 'Permission', 'Stock_Get'),
                        ('AccountManager', 'Permission', 'Stocks_Get'),
                        ('AccountManager', 'Permission', 'SubscriptionAddOn_Create'),
                        ('AccountManager', 'Permission', 'SubscriptionAddOn_Get'),
                        ('AccountManager', 'Permission', 'SubscriptionAddOn_Update'),
                        ('AccountManager', 'Permission', 'Subscription_Create'),
                        ('AccountManager', 'Permission', 'Subscription_Get'),
                        ('AccountManager', 'Permission', 'Subscription_Update'),
                        ('AccountManager', 'Permission', 'Supplier_Create'),
                        ('AccountManager', 'Permission', 'Supplier_Get'),
                        ('AccountManager', 'Permission', 'Supplier_Update'),
                        ('AccountManager', 'Permission', 'Tax_Create'),
                        ('AccountManager', 'Permission', 'Tax_Get'),
                        ('AccountManager', 'Permission', 'Tax_Update'),
                        ('AccountManager', 'Permission', 'Terminal_Create'),
                        ('AccountManager', 'Permission', 'Terminal_Get'),
                        ('AccountManager', 'Permission', 'Terminal_Update'),
                        ('AccountManager', 'Permission', 'User_Create'),
                        ('AccountManager', 'Permission', 'User_Get'),
                        ('AccountManager', 'Permission', 'User_Update'),
                        ('AccountManager', 'Permission', 'Version_Get'),
                        ('AccountManager', 'Permission', 'Warehouse_Create'),
                        ('AccountManager', 'Permission', 'Warehouse_Get'),
                        ('AccountManager', 'Permission', 'Warehouse_Update'),
                        ('AccountManager', 'Permission', 'Webhook_Create'),
                        ('AccountManager', 'Permission', 'Webhook_Get'),

                        ('AccountOwner', 'Permission', 'AccountPaymentMode_Get'),
                        ('AccountOwner', 'Permission', 'Account_Get'),
                        ('AccountOwner', 'Permission', 'Account_GetList'),
                        ('AccountOwner', 'Permission', 'Account_Update'),
                        ('AccountOwner', 'Permission', 'AddOn_Get'),
                        ('AccountOwner', 'Permission', 'AppSource_Delete'),
                        ('AccountOwner', 'Permission', 'AppSource_Get'),
                        ('AccountOwner', 'Permission', 'AppSource_Update'),
                        ('AccountOwner', 'Permission', 'Bay_Create'),
                        ('AccountOwner', 'Permission', 'Bay_Delete'),
                        ('AccountOwner', 'Permission', 'Bay_Get'),
                        ('AccountOwner', 'Permission', 'Bay_Update'),
                        ('AccountOwner', 'Permission', 'Car_Create'),
                        ('AccountOwner', 'Permission', 'Car_Delete'),
                        ('AccountOwner', 'Permission', 'Car_Get'),
                        ('AccountOwner', 'Permission', 'Car_Update'),
                        ('AccountOwner', 'Permission', 'Category_Create'),
                        ('AccountOwner', 'Permission', 'Category_Delete'),
                        ('AccountOwner', 'Permission', 'Category_Get'),
                        ('AccountOwner', 'Permission', 'Category_Update'),
                        ('AccountOwner', 'Permission', 'CompanyClient_Create'),
                        ('AccountOwner', 'Permission', 'CompanyClient_Delete'),
                        ('AccountOwner', 'Permission', 'CompanyClient_Get'),
                        ('AccountOwner', 'Permission', 'CompanyClient_Update'),
                        ('AccountOwner', 'Permission', 'CompanyInvoice_Read'),
                        ('AccountOwner', 'Permission', 'CreditCustomer_GetInvoices'),
                        ('AccountOwner', 'Permission', 'CustomerPayment_Record'),
                        ('AccountOwner', 'Permission', 'Customer_Create'),
                        ('AccountOwner', 'Permission', 'Customer_Delete'),
                        ('AccountOwner', 'Permission', 'Customer_Get'),
                        ('AccountOwner', 'Permission', 'Customer_Update'),
                        ('AccountOwner', 'Permission', 'Item_Create'),
                        ('AccountOwner', 'Permission', 'Item_Delete'),
                        ('AccountOwner', 'Permission', 'Item_Get'),
                        ('AccountOwner', 'Permission', 'Item_Update'),
                        ('AccountOwner', 'Permission', 'LocationSetting_Get'),
                        ('AccountOwner', 'Permission', 'LocationSetting_Update'),
                        ('AccountOwner', 'Permission', 'Location_Get'),
                        ('AccountOwner', 'Permission', 'Location_GetList'),
                        ('AccountOwner', 'Permission', 'Location_Update'),
                        ('AccountOwner', 'Permission', 'Notification_Get'),
                        ('AccountOwner', 'Permission', 'Notification_Update'),
                        ('AccountOwner', 'Permission', 'OrderNote_Create'),
                        ('AccountOwner', 'Permission', 'OrderNote_Get'),
                        ('AccountOwner', 'Permission', 'OrderNote_Update'),
                        ('AccountOwner', 'Permission', 'Order_Create'),
                        ('AccountOwner', 'Permission', 'Package_Create'),
                        ('AccountOwner', 'Permission', 'Package_Delete'),
                        ('AccountOwner', 'Permission', 'Package_Get'),
                        ('AccountOwner', 'Permission', 'Package_Update'),
                        ('AccountOwner', 'Permission', 'PaymentMode_Get'),
                        ('AccountOwner', 'Permission', 'PurchaseBill_Create'),
                        ('AccountOwner', 'Permission', 'PurchaseBills_Get'),
                        ('AccountOwner', 'Permission', 'PurchaseOrder_Approve'),
                        ('AccountOwner', 'Permission', 'PurchaseOrder_Create'),
                        ('AccountOwner', 'Permission', 'PurchaseOrder_Delete'),
                        ('AccountOwner', 'Permission', 'PurchaseOrder_Get'),
                        ('AccountOwner', 'Permission', 'PurchaseOrder_Submit'),
                        ('AccountOwner', 'Permission', 'PurchaseOrder_Update'),
                        ('AccountOwner', 'Permission', 'PurchaseOrders_Get'),
                        ('AccountOwner', 'Permission', 'Quotation_Create'),
                        ('AccountOwner', 'Permission', 'Quotation_Delete'),
                        ('AccountOwner', 'Permission', 'Quotation_Get'),
                        ('AccountOwner', 'Permission', 'Quotation_Update'),
                        ('AccountOwner', 'Permission', 'Reconciliations_Audit'),
                        ('AccountOwner', 'Permission', 'Reconciliations_Create'),
                        ('AccountOwner', 'Permission', 'Reconciliations_Get'),
                        ('AccountOwner', 'Permission', 'Reconciliations_Submit'),
                        ('AccountOwner', 'Permission', 'Reconciliations_Update'),
                        ('AccountOwner', 'Permission', 'Refund_GetHistory'),
                        ('AccountOwner', 'Permission', 'Report_Get'),
                        ('AccountOwner', 'Permission', 'Role_Create'),
                        ('AccountOwner', 'Permission', 'Role_Delete'),
                        ('AccountOwner', 'Permission', 'Role_Get'),
                        ('AccountOwner', 'Permission', 'Role_Update'),
                        ('AccountOwner', 'Permission', 'StockRequest_Approve'),
                        ('AccountOwner', 'Permission', 'StockRequest_Create'),
                        ('AccountOwner', 'Permission', 'StockTransfer_Create'),
                        ('AccountOwner', 'Permission', 'StockTransfer_Get'),
                        ('AccountOwner', 'Permission', 'StockTransfer_Receive'),
                        ('AccountOwner', 'Permission', 'Stock_Get'),
                        ('AccountOwner', 'Permission', 'Stocks_Get'),
                        ('AccountOwner', 'Permission', 'SubscriptionAddOn_Get'),
                        ('AccountOwner', 'Permission', 'Subscription_Get'),
                        ('AccountOwner', 'Permission', 'Supplier_Create'),
                        ('AccountOwner', 'Permission', 'Supplier_Get'),
                        ('AccountOwner', 'Permission', 'Supplier_Update'),
                        ('AccountOwner', 'Permission', 'Tax_Create'),
                        ('AccountOwner', 'Permission', 'Tax_Get'),
                        ('AccountOwner', 'Permission', 'Tax_Update'),
                        ('AccountOwner', 'Permission', 'Terminal_Get'),
                        ('AccountOwner', 'Permission', 'User_Create'),
                        ('AccountOwner', 'Permission', 'User_Delete'),
                        ('AccountOwner', 'Permission', 'User_Get'),
                        ('AccountOwner', 'Permission', 'User_Update'),
                        ('AccountOwner', 'Permission', 'Version_Get'),
                        ('AccountOwner', 'Permission', 'Warehouse_Create'),
                        ('AccountOwner', 'Permission', 'Warehouse_Get'),
                        ('AccountOwner', 'Permission', 'Warehouse_Update'),

                        ('GeneralManager', 'Permission', 'Account_Get'),
                        ('GeneralManager', 'Permission', 'Account_GetList'),
                        ('GeneralManager', 'Permission', 'AddOn_Get'),
                        ('GeneralManager', 'Permission', 'AppSource_Delete'),
                        ('GeneralManager', 'Permission', 'AppSource_Get'),
                        ('GeneralManager', 'Permission', 'AppSource_Update'),
                        ('GeneralManager', 'Permission', 'Bay_Create'),
                        ('GeneralManager', 'Permission', 'Bay_Delete'),
                        ('GeneralManager', 'Permission', 'Bay_Get'),
                        ('GeneralManager', 'Permission', 'Bay_Update'),
                        ('GeneralManager', 'Permission', 'Car_Create'),
                        ('GeneralManager', 'Permission', 'Car_Delete'),
                        ('GeneralManager', 'Permission', 'Car_Get'),
                        ('GeneralManager', 'Permission', 'Car_Update'),
                        ('GeneralManager', 'Permission', 'Category_Create'),
                        ('GeneralManager', 'Permission', 'Category_Delete'),
                        ('GeneralManager', 'Permission', 'Category_Get'),
                        ('GeneralManager', 'Permission', 'Category_Update'),
                        ('GeneralManager', 'Permission', 'CompanyClient_Create'),
                        ('GeneralManager', 'Permission', 'CompanyClient_Delete'),
                        ('GeneralManager', 'Permission', 'CompanyClient_Get'),
                        ('GeneralManager', 'Permission', 'CompanyClient_Update'),
                        ('GeneralManager', 'Permission', 'CompanyInvoice_Read'),
                        ('GeneralManager', 'Permission', 'CustomerPayment_Record'),
                        ('GeneralManager', 'Permission', 'Customer_Create'),
                        ('GeneralManager', 'Permission', 'Customer_Delete'),
                        ('GeneralManager', 'Permission', 'Customer_Get'),
                        ('GeneralManager', 'Permission', 'Customer_Update'),
                        ('GeneralManager', 'Permission', 'Item_Create'),
                        ('GeneralManager', 'Permission', 'Item_Delete'),
                        ('GeneralManager', 'Permission', 'Item_Get'),
                        ('GeneralManager', 'Permission', 'Item_Update'),
                        ('GeneralManager', 'Permission', 'LocationSetting_Get'),
                        ('GeneralManager', 'Permission', 'LocationSetting_Update'),
                        ('GeneralManager', 'Permission', 'Location_Get'),
                        ('GeneralManager', 'Permission', 'Location_GetList'),
                        ('GeneralManager', 'Permission', 'Notification_Update'),
                        ('GeneralManager', 'Permission', 'OrderNote_Create'),
                        ('GeneralManager', 'Permission', 'OrderNote_Get'),
                        ('GeneralManager', 'Permission', 'OrderNote_Update'),
                        ('GeneralManager', 'Permission', 'Order_Create'),
                        ('GeneralManager', 'Permission', 'Package_Create'),
                        ('GeneralManager', 'Permission', 'Package_Delete'),
                        ('GeneralManager', 'Permission', 'Package_Get'),
                        ('GeneralManager', 'Permission', 'Package_Update'),
                        ('GeneralManager', 'Permission', 'PaymentMode_Get'),
                        ('GeneralManager', 'Permission', 'PurchaseBill_Create'),
                        ('GeneralManager', 'Permission', 'PurchaseBills_Get'),
                        ('GeneralManager', 'Permission', 'PurchaseOrder_Approve'),
                        ('GeneralManager', 'Permission', 'PurchaseOrder_Create'),
                        ('GeneralManager', 'Permission', 'PurchaseOrder_Delete'),
                        ('GeneralManager', 'Permission', 'PurchaseOrder_Get'),
                        ('GeneralManager', 'Permission', 'PurchaseOrder_Submit'),
                        ('GeneralManager', 'Permission', 'PurchaseOrder_Update'),
                        ('GeneralManager', 'Permission', 'PurchaseOrders_Get'),
                        ('GeneralManager', 'Permission', 'Quotation_Create'),
                        ('GeneralManager', 'Permission', 'Quotation_Delete'),
                        ('GeneralManager', 'Permission', 'Quotation_Get'),
                        ('GeneralManager', 'Permission', 'Quotation_Update'),
                        ('GeneralManager', 'Permission', 'Reconciliations_Audit'),
                        ('GeneralManager', 'Permission', 'Reconciliations_Create'),
                        ('GeneralManager', 'Permission', 'Reconciliations_Get'),
                        ('GeneralManager', 'Permission', 'Reconciliations_Submit'),
                        ('GeneralManager', 'Permission', 'Reconciliations_Update'),
                        ('GeneralManager', 'Permission', 'Refund_GetHistory'),
                        ('GeneralManager', 'Permission', 'Report_Get'),
                        ('GeneralManager', 'Permission', 'Role_Delete'),
                        ('GeneralManager', 'Permission', 'Role_Get'),
                        ('GeneralManager', 'Permission', 'Role_Update'),
                        ('GeneralManager', 'Permission', 'StockRequest_Approve'),
                        ('GeneralManager', 'Permission', 'StockRequest_Create'),
                        ('GeneralManager', 'Permission', 'StockTransfer_Create'),
                        ('GeneralManager', 'Permission', 'StockTransfer_Get'),
                        ('GeneralManager', 'Permission', 'StockTransfer_Receive'),
                        ('GeneralManager', 'Permission', 'Stock_Get'),
                        ('GeneralManager', 'Permission', 'Stocks_Get'),
                        ('GeneralManager', 'Permission', 'SubscriptionAddOn_Get'),
                        ('GeneralManager', 'Permission', 'Subscription_Get'),
                        ('GeneralManager', 'Permission', 'Supplier_Create'),
                        ('GeneralManager', 'Permission', 'Supplier_Get'),
                        ('GeneralManager', 'Permission', 'Supplier_Update'),
                        ('GeneralManager', 'Permission', 'Tax_Create'),
                        ('GeneralManager', 'Permission', 'Tax_Get'),
                        ('GeneralManager', 'Permission', 'Tax_Update'),
                        ('GeneralManager', 'Permission', 'Terminal_Get'),
                        ('GeneralManager', 'Permission', 'User_Create'),
                        ('GeneralManager', 'Permission', 'User_Delete'),
                        ('GeneralManager', 'Permission', 'User_Get'),
                        ('GeneralManager', 'Permission', 'User_Update'),
                        ('GeneralManager', 'Permission', 'Version_Get'),
                        ('GeneralManager', 'Permission', 'Warehouse_Create'),
                        ('GeneralManager', 'Permission', 'Warehouse_Get'),
                        ('GeneralManager', 'Permission', 'Warehouse_Update'),

                        ('BranchManager', 'Permission', 'Account_Get'),
                        ('BranchManager', 'Permission', 'Account_GetList'),
                        ('BranchManager', 'Permission', 'AccountPaymentMode_Get'),
                        ('BranchManager', 'Permission', 'AppSource_Update'),
                        ('BranchManager', 'Permission', 'Bay_Get'),
                        ('BranchManager', 'Permission', 'Bay_GetList'),
                        ('BranchManager', 'Permission', 'Bay_Update'),
                        ('BranchManager', 'Permission', 'Car_Create'),
                        ('BranchManager', 'Permission', 'Car_Get'),
                        ('BranchManager', 'Permission', 'Car_Update'),
                        ('BranchManager', 'Permission', 'Category_Get'),
                        ('BranchManager', 'Permission', 'Category_Update'),
                        ('BranchManager', 'Permission', 'CompanyClient_Create'),
                        ('BranchManager', 'Permission', 'CompanyClient_Get'),
                        ('BranchManager', 'Permission', 'CompanyClient_Update'),
                        ('BranchManager', 'Permission', 'CompanyInvoice_Read'),
                        ('BranchManager', 'Permission', 'CustomerPayment_Record'),
                        ('BranchManager', 'Permission', 'Customer_Create'),
                        ('BranchManager', 'Permission', 'Customer_Update'),
                        ('BranchManager', 'Permission', 'Item_Get'),
                        ('BranchManager', 'Permission', 'Item_Update'),
                        ('BranchManager', 'Permission', 'Location_Get'),
                        ('BranchManager', 'Permission', 'Location_GetList'),
                        ('BranchManager', 'Permission', 'OrderNote_Create'),
                        ('BranchManager', 'Permission', 'OrderNote_Get'),
                        ('BranchManager', 'Permission', 'OrderNote_Update'),
                        ('BranchManager', 'Permission', 'Order_Create'),
                        ('BranchManager', 'Permission', 'Package_Get'),
                        ('BranchManager', 'Permission', 'Package_Update'),
                        ('BranchManager', 'Permission', 'PurchaseOrder_Approve'),
                        ('BranchManager', 'Permission', 'PurchaseOrder_Submit'),
                        ('BranchManager', 'Permission', 'PurchaseOrder_Update'),
                        ('BranchManager', 'Permission', 'Quotation_Create'),
                        ('BranchManager', 'Permission', 'Quotation_Update'),
                        ('BranchManager', 'Permission', 'Reconciliations_Audit'),
                        ('BranchManager', 'Permission', 'Reconciliations_Submit'),
                        ('BranchManager', 'Permission', 'Reconciliations_Update'),
                        ('BranchManager', 'Permission', 'StockRequest_Approve'),
                        ('BranchManager', 'Permission', 'StockTransfer_Receive'),
                        ('BranchManager', 'Permission', 'Supplier_Update'),
                        ('BranchManager', 'Permission', 'User_Update'),
                        ('BranchManager', 'Permission', 'Version_Get'),
                        ('BranchManager', 'Permission', 'Warehouse_Get'),
                        ('BranchManager', 'Permission', 'Warehouse_Update'),

                              
                        ('StockManager', 'Permission', 'Account_Get'),
                        ('StockManager', 'Permission', 'Account_GetList'),
                        ('StockManager', 'Permission', 'Category_Create'),
                        ('StockManager', 'Permission', 'Category_Delete'),
                        ('StockManager', 'Permission', 'Category_Get'),
                        ('StockManager', 'Permission', 'Category_Update'),
                        ('StockManager', 'Permission', 'Item_Create'),
                        ('StockManager', 'Permission', 'Item_Delete'),
                        ('StockManager', 'Permission', 'Item_Get'),
                        ('StockManager', 'Permission', 'Item_Update'),
                        ('StockManager', 'Permission', 'Location_Get'),
                        ('StockManager', 'Permission', 'Location_GetList'),
                        ('StockManager', 'Permission', 'Package_Create'),
                        ('StockManager', 'Permission', 'Package_Delete'),
                        ('StockManager', 'Permission', 'Package_Get'),
                        ('StockManager', 'Permission', 'PurchaseBill_Create'),
                        ('StockManager', 'Permission', 'PurchaseBills_Get'),
                        ('StockManager', 'Permission', 'PurchaseOrder_Create'),
                        ('StockManager', 'Permission', 'PurchaseOrder_Delete'),
                        ('StockManager', 'Permission', 'PurchaseOrder_Get'),
                        ('StockManager', 'Permission', 'PurchaseOrder_Update'),
                        ('StockManager', 'Permission', 'PurchaseOrders_Get'),
                        ('StockManager', 'Permission', 'Quotation_Update'),
                        ('StockManager', 'Permission', 'Reconciliations_Audit'),
                        ('StockManager', 'Permission', 'Reconciliations_Create'),
                        ('StockManager', 'Permission', 'Reconciliations_Get'),
                        ('StockManager', 'Permission', 'Reconciliations_Submit'),
                        ('StockManager', 'Permission', 'Reconciliations_Update'),
                        ('StockManager', 'Permission', 'Report_Get'),
                        ('StockManager', 'Permission', 'StockRequest_Create'),
                        ('StockManager', 'Permission', 'StockTransfer_Create'),
                        ('StockManager', 'Permission', 'StockTransfer_Get'),
                        ('StockManager', 'Permission', 'StockTransfer_Receive'),
                        ('StockManager', 'Permission', 'Stock_Get'),
                        ('StockManager', 'Permission', 'Stocks_Get'),
                        ('StockManager', 'Permission', 'Supplier_Create'),
                        ('StockManager', 'Permission', 'Supplier_Get'),
                        ('StockManager', 'Permission', 'Supplier_Update'),
                        ('StockManager', 'Permission', 'Tax_Create'),
                        ('StockManager', 'Permission', 'Tax_Get'),
                        ('StockManager', 'Permission', 'Version_Get'),
                        ('StockManager', 'Permission', 'Warehouse_Create'),
                        ('StockManager', 'Permission', 'Warehouse_Get'),
                        ('StockManager', 'Permission', 'Warehouse_Update'),
   
                              
                        ('Cashier', 'Permission', 'Account_Get'),
                        ('Cashier', 'Permission', 'Account_GetList'),
                        ('Cashier', 'Permission', 'AccountPaymentMode_Get'),
                        ('Cashier', 'Permission', 'Car_Create'),
                        ('Cashier', 'Permission', 'Car_Get'),
                        ('Cashier', 'Permission', 'Category_Get'),
                        ('Cashier', 'Permission', 'CompanyClient_Create'),
                        ('Cashier', 'Permission', 'CompanyClient_Get'),
                        ('Cashier', 'Permission', 'Customer_Create'),
                        ('Cashier', 'Permission', 'Item_Get'),
                        ('Cashier', 'Permission', 'Location_Get'),
                        ('Cashier', 'Permission', 'Location_GetList'),
                        ('Cashier', 'Permission', 'OrderNote_Create'),
                        ('Cashier', 'Permission', 'OrderNote_Get'),
                        ('Cashier', 'Permission', 'Order_Create'),
                        ('Cashier', 'Permission', 'Package_Get'),
                        ('Cashier', 'Permission', 'Quotation_Create'),
                        ('Cashier', 'Permission', 'Version_Get'),
                              
                        ('Technician', 'Permission', 'Account_Get'),
                        ('Technician', 'Permission', 'Account_GetList'),
                        ('Technician', 'Permission', 'Bay_Get'),
                        ('Technician', 'Permission', 'Bay_Update'),
                        ('Technician', 'Permission', 'Car_Get'),
                        ('Technician', 'Permission', 'Item_Get'),
                        ('Technician', 'Permission', 'Location_Get'),
                        ('Technician', 'Permission', 'Location_GetList'),
                        ('Technician', 'Permission', 'OrderNote_Create'),
                        ('Technician', 'Permission', 'OrderNote_Get'),
                        ('Technician', 'Permission', 'OrderNote_Update'),

                        ('Assistant', 'Permission', 'Account_Get'),
                        ('Assistant', 'Permission', 'Account_GetList'),
                        ('Assistant', 'Permission', 'Bay_Get'),
                        ('Assistant', 'Permission', 'Item_Get'),
                        ('Assistant', 'Permission', 'Location_Get'),
                        ('Assistant', 'Permission', 'Location_GetList'),
                        ('Assistant', 'Permission', 'OrderNote_Get');
            """))
        logging.info(f'DB setuped successfully')


    except Exception as e:
        logging.error(f'Failed to Setup the DB: {e}')
        raise    

if __name__ == '__main__':
    main()
